### ISSUE TITLE
Allow control over whether data is returned as an array or not

### ISSUE THREAD

**Issue by iand675** [toddmohney/json-api#27]
Hi, I'm experimenting a bit with [ember-data](https://github.com/emberjs/data), which incidentally inspired a lot of the design of the json-api spec. Whenever I return a 0-N query that happens to have one item, it is returned unwrapped (e.g. not in a JSON array). This causes ember-data to complain via assertion error that results from the query API should always be returned in an array.

I'd like to propose a few solutions:

1. splitting `mkDocument` (non-breaking) into something like:

```
mkDocument = ... old behavior ...
mkDocumentSingle :: a -> Maybe Links -> Maybe Meta -> Document a
mkDocumentArray :: [a] -> Maybe Links -> Maybe Meta -> Document a
```

2. Specify via ADT (breaking, but seems a bit cleaner)

```
data DataField a = Single a | Plural [a]

mkDocument :: DataField a -> Maybe Links -> Maybe Meta -> Document
```

**Comment by YLiLarry** [comment]
I can confirm this needs to be improved.
Specifically, the current mkDocument interface lacks of the ability to create an array that has 1 item.

**Comment by toddmohney** [comment]
Ah, I see what you mean. These are good suggestions.
I can make these changes soon. Alternatively, if you would like to submit a pull request, I'd be happy to review it so you can have the update sooner!

Thanks!
