### ISSUE TITLE
Support Pagination in Links Object

### ISSUE THREAD

**Issue by toddmohney** [toddmohney/json-api#7]
Specification:
http://jsonapi.org/format/#fetching-pagination

**Comment by shirren** [comment]
@toddmohney this would be a handy feature for us on our project. May I submit a PR with this feature?

**Comment by toddmohney** [comment]
@shirren Of course! Thanks!

**Comment by shirren** [comment]
@toddmohney thoughts on whether this feature should support a cursor based strategy?

**Comment by toddmohney** [comment]
@shirren just took a look at your draft PR. I think the page/offset strategy works well here.

**Comment by shirren** [comment]
@toddmohney thanks for checking it out. The tests pass, so good there. But I am thinking of updating the README with instrsuctions on how to use the Pagination. Should we make it part of this PR or another one?

**Comment by toddmohney** [comment]
@shirren I think updating the README as part of this PR makes a lot of sense. Thanks!

**Comment by shirren** [comment]
@toddmohney done. I've updated the README with an example on how to add pagination links to the payload.

**Comment by toddmohney** [comment]
Resolved by https://github.com/toddmohney/json-api/pull/35
